#!/bin/bash
# STN Landing Page Development Commands

echo "🚀 STN Landing Page - Development Setup"
echo "========================================"
echo ""
echo "Available commands:"
echo ""
echo "1. npm run dev          - Start development server"
echo "2. npm run build        - Build for production"
echo "3. npm run lint         - Lint & fix code"
echo "4. npm run format       - Format code with Prettier"
echo "5. npm run format:check - Check formatting"
echo "6. npm run types        - Type check TypeScript"
echo ""
echo "========================================"
echo ""
echo "Project Structure:"
echo "├── resources/js/pages/welcome.tsx         - Main landing page"
echo "├── resources/js/components/"
echo "│   ├── Navbar.tsx                         - Header navigation"
echo "│   ├── HeroCarousel.tsx                   - Hero banner"
echo "│   ├── ProductSection.tsx                 - Products showcase"
echo "│   ├── StatsSection.tsx                   - Statistics"
echo "│   ├── AboutSection.tsx                   - About company"
echo "│   ├── GallerySection.tsx                 - Portfolio gallery"
echo "│   ├── TestimonialSection.tsx             - Client testimonials"
echo "│   ├── ContactSection.tsx                 - Contact form"
echo "│   ├── CTASection.tsx                     - Call-to-action"
echo "│   ├── BrosurModal.tsx                    - Brosur modal"
echo "│   └── Footer.tsx                         - Footer section"
echo "└── docs/"
echo "    ├── LANDING_PAGE_README.md             - Full documentation"
echo "    └── LANDING_PAGE_STRUCTURE.md          - Visual structure"
echo ""
echo "========================================"
echo ""
echo "🎯 Next Steps:"
echo "1. Run 'npm run dev' to start development server"
echo "2. Visit http://localhost:5173 to preview"
echo "3. Customize content in component files"
echo "4. Replace placeholder images with real ones"
echo ""
echo "✨ Happy coding!"
